### ISSUE TITLE
Special characters

### ISSUE THREAD

**Issue by winniederidder** [dodona-edu/papyros#10]
Non-standard characters (such as Mac quotes and probably emojis) are rejected by both the Worker and Comlink. A way must be found to handle a broader set of characters.
Example trace:
SyntaxError: invalid character '“' (U+201C)
comlink.ts:544Unhandled Promise Rejection: DataCloneError: The object can not be cloned.

After some research, it seems the DataCloneError only occurs on Safari. Chrome handles it just fine.

**Comment by pdawyndt** [comment]
Non-standard = Unicode? The latter is pretty standard nowadays.

**Comment by winniederidder** [comment]
The real issue is the shape of the error on Safari and not the characters themselves as I originally thought. Should be solved in #12
