### ISSUE TITLE
Simplify input handling

### ISSUE THREAD

**Issue by winniederidder** [dodona-edu/papyros#100]
The service worker makes various things quite complicated. Support for SharedArrayBuffers is also growing. It would be better to fully switch over to SharedArrayBuffers to make everything work simply and efficiently.
Adding the required headers at the server side to support this will be needed. 
More specifically, the Cross-Origin-Embedder-Policy header must be set to 'require-corp', and the Cross-Origin-Resource-Policy must be set correctly (preferably the least broad option) to still allow fetching resources to work correctly. For example in Dodona, the sandboxed iframes must still be able to load code and stylesheets even when isolated.

**Comment by alexmojaki** [comment]
I think it's good to serve headers from the server so that the service worker isn't always needed, but I don't see a reason not to use service workers as a fallback when SharedArrayBuffers aren't available. sync-message will hide most of the complexity.

**Comment by winniederidder** [comment]
We have the multi-line input that could function as a fallback. The service worker contains a bunch of added complexity and requires manual serving by users of the package. The question is then whether it is worth maintaining.
