### ISSUE TITLE
FriendlyTraceback not available for syntax errors

### ISSUE THREAD

**Issue by winniederidder** [dodona-edu/papyros#103]
When opening Papyros and quickly launching a program with a compilation error, it is possible that the error is not formatted properly as FriendlyTraceback is not yet available reason.
Reason: PythonRunner::Runner::pre_run is not async and tries to compile the code, catching any SyntaxErrors itself and passing this error to Runner::serialize_syntax_error and by default thus to Runner::serialize_traceback. In Papyros, we expect to catch this error ourself and awaiting the installation before handling the exception. In this case, we cannot catch the exception ourselves, causing friendly_traceback to not be available.

A possible solution is to always await the ft-promise in Papyros::run_async before compiling. Alternatively, more methods in PythonRunner could be made async for flexiblity.
@alexmojaki Thoughts?

**Comment by alexmojaki** [comment]
ugh, async is such a pain sometimes.

python_runner could get some extra methods for papyros to override, like `async def pre_serialize_error` or something, which would just contain `await ft` for you and would allow getting rid of the copied `run_async` in papyros.

In the long term this may become irrelevant. futurecoder downloads its dependencies directly in parallel to loading pyodide, and I'd like to implement that in a generic package and thus for papyros.

**Comment by winniederidder** [comment]
I can move the ```await ft``` higher then while keeping this issue open to link back to when parallel downloading is possible.
