### ISSUE TITLE
Clean file path to executed Python file

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/papyros#105]
Execute the (invalid) Python code
```python
// syntax error
```
And you get the error message
```
SyntaxError traceback:
  File "HOME:/my_code.py", line 1
    // syntax error
    ^
```
that needs a cleaner file path to the executed Python file (looks like a MS Windows file path, but it isn't).

**Comment by winniederidder** [comment]
Yes, HOME seems to have been added in a recent update to FriendlyTraceback as this originally wasn't there. I could strip it away, but a more general approach to the error handling might be even more useful.
@alexmojaki Do you have any (future) plans to make the Exception handling as used in FutureCoder also available in a package?

**Comment by alexmojaki** [comment]
You should be able to copy the `serialize_traceback` and `serialize_syntax_error` from futurecoder into your python code to try it out, although you'll have to mash everything into one file. A lot of it could be moved into `stack_data` to mirror the formatting code, it's just a little too opinionated at the moment.

But you'll need to port the code in https://github.com/alexmojaki/futurecoder/blob/9217acb168d1adadaa244980b4742b9f9a145c0b/frontend/src/shell/TerminalMessage.jsx#L42-L157 from React to your own frontend rendering system, which might be a bit messier.

**Comment by winniederidder** [comment]
Absolute path fixed this specific issue. If we want to update the error display, a new issue should be opened detailing our needs and goals.
