### ISSUE TITLE
Gutter does not run across entire code

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/papyros#124]
The gutter stops where the viewport of the editor stops. This can be seen when scrolling down code that is longer than the initial viewport.

![image](https://user-images.githubusercontent.com/5736113/163848609-feb0efd9-c92a-4247-9752-111d4f5e2e66.png)

**Comment by winniederidder** [comment]
Fixed in the latest commit in the Dodona repository: https://github.com/dodona-edu/dodona/pull/3453#issuecomment-1105828260
