### ISSUE TITLE
Toggling between langauges duplicates output

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/papyros#129]
Toggling between Dutch and English duplicates the content of the output field:

![image](https://user-images.githubusercontent.com/5736113/164716059-fa35fd3a-b5fe-40c6-b803-00210427f0c1.png)

**Comment by pdawyndt** [comment]
It also resets the "programming language" and "example" dropdowns.

**Comment by winniederidder** [comment]
Resolved by the latest commits on https://github.com/dodona-edu/papyros/pull/128.
