### ISSUE TITLE
Integrated version in Dodona keeps loading on Mac/Safari

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/papyros#136]
On Mac/Safari browsers (both desktop and iPad) the version of Papyros that is integrated in Dodona keeps loading after initial display. This has now been observed on multiple machines. Does not happen on other Mac browsers, and also does not happen with the standalone version on Mac/Safari.

![image](https://user-images.githubusercontent.com/5736113/165939738-64ad35eb-2b71-471e-b823-9a7666c5ac97.png)

Observers: Peter Dawyndt, Dominiek Vandewalle, computer science student

**Comment by winniederidder** [comment]
Isn't this related to https://github.com/dodona-edu/dodona/pull/3563, as the service worker wasn't correctly resolved so nothing worked? This has been merged, but I don't know if it was also deployed. @bmesuere ?

**Comment by chvp** [comment]
Two releases have been cut since that PR was merged, so this is definitely deployed.

**Comment by winniederidder** [comment]
After some inspection, it seems that Safari does not support the CSP policy worker-src, causing the worker to not be loaded. I will work on a fix and open a PR on Dodona.

**Comment by bmesuere** [comment]
In addition to the proposed fix, it might be a good idea to show a more user friendly error message when loading doesn't succeed after a few seconds.

**Comment by pdawyndt** [comment]
Together with the message, maybe also provide the option to reload the Python runtime.

**Comment by winniederidder** [comment]
The error message and reload option will be added in a separate PR.
