### ISSUE TITLE
Interrupt code execution gracefully

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/papyros#153]
Interrupting code like

```python
while True:
    pass
```

produces an `undefined traceback` in the output area

![image](https://user-images.githubusercontent.com/5736113/166231028-0db4133c-7469-46c9-adcd-6082081781a9.png)

in the version integrated in Dodona. Never saw this behaviour in the standalone version.

**Comment by winniederidder** [comment]
I'm pretty sure this is linked to SharedArrayBuffers no longer being available and the code in question not using comsync-functionality. This means that the interrupt kills the worker, which is more costly. I'll look into handing this case in a better way.
