### ISSUE TITLE
More advanced handling of large output volumes

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/papyros#157]
Large volumes of output yield issues for the IDE:

1. passing large volumes of messages between service worker and UI may saturate communication channel (still an issue?)
2. showing all output in output field may yield large memory footprint

The current solutions only shows the initial lines of output in the output field and allows to download all output in a text file (still requires to store all output somewhere). However, running code like

```python
for index in range(10000):
    print(index)
```

1. truncates the output to the first few lines; exact point where truncation is done differs between runs
2. shows a message `Output truncated. Click here to download the results.` that can be clicked to download the complete output in a file; at least I would put this message in the output window (after the last line displayed) such that no additional space is needed for this message in the UI

(1) in itself gives the impression that not all output is generated (if not seen together with the message that the output was truncated). I would find it more natural to keep the content of the output field restricted by starting to remove lines at the beginning of the output (as is done in most IDEs) as soon as a certain buffer size is exceeded (maybe also take into account total length of the buffer, and not purely the number of lines) so that you get too see the end of the output. Such an approach would keep the UI responsive for code like

```python
import time

index = 1
while True:
    print(index)
    index += 1
    time.sleep(0.02)
```

In this case, the output halts (now consistently after 500 lines) which gives the impression that no more output is generated. This is confusing, because due to the infinite loop the message that indicates the output is truncated is never displayed. If we always would see the last n lines (again, with option to make n dependent on output size instead of using a fixed n), you would still see that the program keeps generating new output. I would then also no longer provide the option to download the entire output, as I would actually throw away output that is no longer displayed to make sure that buffer size overflows (which is still the case now).

Handling the output buffer (and throwing away lines at the beginning) is something I would to outside the service worker. As such, the service worker can focus only on running the code and passing new output to the UI.

**Comment by winniederidder** [comment]
Since the Comlink issue occurs when too many messages are being passed, showing the latest output is simply not possible without risking thread communication to fail.

**Comment by winniederidder** [comment]
> Handling the output buffer (and throwing away lines at the beginning) is something I would to outside the service worker. As such, the service worker can focus only on running the code and passing new output to the UI.

The issue lies in passing new output to the UI, so the WebWorker has to be the one managing the queue. Reducing the message load is only possible by queueing at the sending side.

**Comment by winniederidder** [comment]
Since showing the last output is not possible, I could show an overflow-message earlier informing the user that the output has been capped during the run.
The output gets truncated at different times due to internal time-based buffering. Output is concatenated before sending it through to also limit the amount of messages passed in a given time frame. The restriction on the shown output is based on the amount of lines, so this varies depending on how many messages were concatenated before the time expired.

So as far as fixing goes, other than showing a message earlier, not much can be done at this point. Thoughts @pdawyndt ?
