### ISSUE TITLE
Service worker limbo

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/papyros#158]
Here's an example on how the service worker can get stuck. 

1. Run this code for a while (piling up output in the service worker):

  ```
  import time
  
  index = 1
  while True:
      print(index)
      index += 1
      time.sleep(0.02)
  ```
2. Click the `Stop` button (won't recover soon because has to clear a large buffer)
3. Reload the page. This keeps showing the alert upon each page reload

![image](https://user-images.githubusercontent.com/5736113/166690162-a7a740dc-9063-4c31-8316-163c2bee0a57.png)

4. Can only recover from this with a hard page refresh.

**Comment by pdawyndt** [comment]
Saw the issue already a couple of times yesterday. Was talking about it to Bart, and then hitting it again when I truying to experiment with the "large output volume" handling today.

**Comment by pdawyndt** [comment]
No example now, but will keep an eye on it while experimenting with Papyros.

**Comment by alexmojaki** [comment]
Here's a fun use case for this kind of code:

```python
import time

for c in 'Look at this cool typing effect!!!':
    print(c, end='')
    time.sleep(0.02)
```

By the way, the overall problem also happens on futurecoder.

**Comment by pdawyndt** [comment]
Nice example of smooth message passing from service worker. Made it somewhat more pythonic

```python
import time

quote = """Bridgekeeper: "What… is your name?"
King Arthur: "It is Arthur – King of the Britons."
Bridgekeeper: "What… is your quest?"
King Arthur: "To seek the Holy Grail.
Bridgekeeper: "What… is the air-speed velocity of an unladen swallow?"
King Arthur: "What do you mean? An African or a European swallow?"
Bridgekeeper: "I don't know that. Aaaaaaaaagh!"
"""

for character in quote:
    print(character, end='')
    time.sleep(0.01)
```
