### ISSUE TITLE
Avoid closing the Papyros panel

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/papyros#161]
When clicking escape in the Papyros editor (e.g. to dismiss code completion windows), this also closes the Papyros panel in  Dodona. Preferably, the latter should not happen.

![image](https://user-images.githubusercontent.com/5736113/167078165-e871265a-cd0f-42cb-a628-749f369a109f.png)

Dismissing the above windows using the escape key, also dismisses the IDE panel.

**Comment by winniederidder** [comment]
Do we want the offcanvas-component to be closed when pressing escape when autocompletions are not shown? Or can I just disable escape closing Papyros in Dodona?

**Comment by bmesuere** [comment]
I would disable escape to close entirely

**Comment by winniederidder** [comment]
Closing this issue as its state is being tracked over at the Dodona-repository in https://github.com/dodona-edu/dodona/pull/3622.
