### ISSUE TITLE
Translate and style search & replace toolbar

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/papyros#207]
No Dutch translation of "search and replace" toolbar (ctrl-F).

![image](https://user-images.githubusercontent.com/5736113/170825621-b17ed9c8-51e2-4a85-b928-2871f9572815.png)

**Comment by pdawyndt** [comment]
Button styling also deviates from run-stop-copy buttons and from other styling used in Dodona.

**Comment by winniederidder** [comment]
The translation part will likely follow the example given in https://codemirror.net/6/examples/translate/
