### ISSUE TITLE
Time to first autocompletion is high

### ISSUE THREAD

**Issue by kselectride** [dodona-edu/papyros#255]
This might not be an issue due to papyros itself, but pyodide or jedi or codemirror (or something else even). Basically, typing a key takes a while for the autocomplete window to pop up, even after it seems like the worker is loaded.

**Comment by winniederidder** [comment]
Indeed, after enabling autocompletion there was no immediate trigger for completions (this however was the default case for linting, so seems to be an inconsistency within CodeMirror). This means that if you were typing and then stopped before Jedi was initialized, you would see no results. I added an immediate trigger for this case that you get completions when it's ready. If you keep typing, you will get completions as soon as everything is setup.
