### ISSUE TITLE
Reading input is too slow

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/papyros#27]
Reading input from stdin (`input()`) that has been preset in the input box is way too slow, even for a few lines of input.

**Comment by alexmojaki** [comment]
Seems fine for me?

**Comment by pdawyndt** [comment]
When I tested with this code
```python
for _ in range(6):
    name = input()
    print(f'Hello, {name}!')
```
and this input on stdin
```
Alice
Bob
Claire
Dave
Erica
Fred
```
it took about one second for each name to appear. Now it indeed seems a lot faster, but I now also get the `None` issue (#56).

**Comment by pdawyndt** [comment]
Works now.

**Comment by pdawyndt** [comment]
Performance issue also seems gone (before it took about a second before the next input was processed).

**Comment by pdawyndt** [comment]
Also works on iPad, but there the one-second-delay is still there. I guess this due to the fallback mechanism for input handling that is actived in Safari?

**Comment by alexmojaki** [comment]
Ah, I get the same thing on Desktop Safari in BrowserStack. What's this fallback mechanism? How do you handle input in Safari?

**Comment by alexmojaki** [comment]
This is not solved, it still takes about a second to read each line of batch input in Safari. It can be solved by sending all the batch input in advance and tweaking the stdin patching, it doesn't have to use the same method for reading prefilled batch input as interactive input.

**Comment by alexmojaki** [comment]
This was solved by sync-message.
