### ISSUE TITLE
Key binding for running the code

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/papyros#36]
Investigate if it would be useful to have a shortkey for running the code.

**Comment by winniederidder** [comment]
Adding it is easy, the question is which keybind is not yet used and intuitive for the user (e.g. many Ctrl keybinds are already in use). I drafted up a version [here](https://github.com/dodona-edu/papyros/tree/issue36/run-code-keybind) using Ctrl-Alt-r, which might be slower than just clicking the button, while not being visually disabled while loading or running other code.

**Comment by pdawyndt** [comment]
Seems like a good starting point. Changing the key binding to something else could be done in a second iteration.

**Comment by alexmojaki** [comment]
I suggest Ctrl+Enter (that's what I've gone with in my similar project)

**Comment by winniederidder** [comment]
That indeed sounds like a good suggestion. I originally didn't use this as CodeMirror 6 uses it in their [default key map](https://codemirror.net/6/docs/ref/#commands.defaultKeymap), but this seems to be coupled to the insertBlankLine, which according to me should be using Shift-Enter instead (supported by e.g. Messenger and Discord, where Messenger also supports Ctrl-Enter but of course they cannot run code :p)
