### ISSUE TITLE
Use monospace font for input and output

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/papyros#39]
Now that we use a code editor with a monospace font, we should also use a monospace font (ideally the same one) for the input and output.

**Comment by pdawyndt** [comment]
Consider using the same code editor for input and output (same representation, same manipulation).

**Comment by winniederidder** [comment]
@pdawyndt Are you satisfied with the current fonts used?

**Comment by alexmojaki** [comment]
(the reason I didn't say my PR closes this issue is that I didn't touch the interactive/batch input areas)

**Comment by winniederidder** [comment]
That is ok, the fonts were changed at some point in a different PR.
