### ISSUE TITLE
Support code completion

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/papyros#40]
Support code completion in Python code editor.

**Comment by winniederidder** [comment]
Which kind of code completion are we aiming for? For instance, the default support in JavaScript is a couple of snippets (such as loop and function definitions). Do we want the same for Python, and more (such as autocompleting variable/function names) or even an IntelliSense level?

**Comment by pdawyndt** [comment]
Ideally: full featured code completion, but more down to earth e.g. code completion as supported in Jupyter Notebooks. But this feature is low priority. I was just adding this as an issue to keep

**Comment by pdawyndt** [comment]
CodeMirror: [hook](https://codemirror.net/doc/manual.html#addon_show-hint)

**Comment by bmesuere** [comment]
That link points to the docs of the old version of CM. Version 6 has an extra prefix in the URL: https://codemirror.net/6/docs/

**Comment by winniederidder** [comment]
I am aware of that link, but I should have mentioned it here myself. I contacted the maintainer of CodeMirror 6 and asked if it were possible to provide some more documentation on how to use the autocompletion-features. I am very grateful to him for providing it swiftly and thoroughly.
