### ISSUE TITLE
Reduce time for initial page rendering

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/papyros#44]
Currently it takes too long before the page is initially rendered.

**Comment by winniederidder** [comment]
A big factor in this slowness is the reload that is done to enable SharedArrayBuffers if possible, to allow for asynchronous input. So the best thing we can do to speedup loading, is removing this input and requiring the user to provide all input beforehand. This would remove the complexity of the serviceWorker etc and allow everything to be done in a single load.

**Comment by alexmojaki** [comment]
SharedArrayBuffer can be enabled without using a service worker at all by configuring the cross-origin isolation headers directly in your web server.

Even for Safari, the service worker can be enabled without a page reload using `clients.claim()`.

**Comment by winniederidder** [comment]
> SharedArrayBuffer can be enabled without using a service worker at all by configuring the cross-origin isolation headers directly in your web server.
> 
The web server part might be tricky. On the one hand, when using this package in a different project, you might not have this capability (such as when deploying it on GitHub pages, where this option cannot be configured yet). Also, this might be something you don't want everywhere on your site, only where the Papyros-part lives. From a security standpoint I would think that specifying it server side is better. @bmesuere Do we have such fine-grained control and are we willing to enable this? Could be done much later in the process when the integration is completed, depending on the impact we see it has on users and the speed-up it might achieve.

**Comment by alexmojaki** [comment]
Are the headers being served from the server itself now, or is this being closed for some other reason?

**Comment by winniederidder** [comment]
This issue was about the initial page rendering, which appears to be quite fast. We recommend enabling SharedArrayBuffers, but the page reload can be disabled even when using service workers, so I consider this issue resolved.
