### ISSUE TITLE
Papyros in embedded mode can't run/execute code in create-react-app react app in production build, but runs in local dev mode

### ISSUE THREAD

**Issue by batmilkyway** [dodona-edu/papyros#451]
I'm not really sure exactly why, but everything runs perfectly in the local dev mode, but when I build the production bundle the autocomplete and linting works, using python, but running code doesn't. I've traced the issue down to `CodeRunner.runCode`, specifically the line
```javascript
await backend.call(backend.workerProxy.runCode, code, mode);
```
as far as I can tell, the `.call` method never actually gets invoked, but since it works in dev, there's probably a build/bundling issue. I did have to use React App Rewired to get workers to load properly, so I'm wondering if that's the issue. the config is

```javascript
module.exports = {
    // Update webpack config to use custom loader for worker files
    webpack: (config) => {
        // Note: It's important that the "worker-loader" gets defined BEFORE the TypeScript loader!
        config.module.rules.unshift({
            test: /\.worker\.ts$/,
            use: {
                loader: 'worker-loader',
                options: {
                    // Use directory structure & typical names of chunks produces by "react-scripts"
                    filename: 'static/js/[name].[contenthash:8].js',
                },
            },
        });
        config.experiments = {topLevelAwait: true}

        return config;
    },
};
```
But again, autocomplete with python works fine, so the python worker gets loaded, but running code doesn't work. A running example can be found at https://glittering-narwhal-96bc3e.netlify.app/. As can be seen, the autocomplete works.

I tried looking at the papyros webpack config, but it's not obvious to me.

**Comment by bmesuere** [comment]
@winniederidder do you have an idea what goes wrong here?

**Comment by winniederidder** [comment]
Bundling was never a pleasant experience while developing this :P . From what I can see, the given config to load workers is not an exact match of Papyros, as `options: {
						inline: 'no-fallback'
					}` is not specified when loading workers.  So my first suggestions would be to add that to your config and try again.
If that doesn't solve the problem, then ideally you would extend your demo app to also provide functionality to run the code so debugging on our side is easier, as the running example you linked does not provide this functionality. Don't forget to also share the repository itself then so we can reproduce the issue easily.

**Comment by batmilkyway** [comment]
They you so much for replying! I will follow up tomorrow with a codesandbox, before I go, I figured I'd put the error message that was actually getting silenced by the try/catch block:

```
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Worker': function(e){var t;o&&"init"!==e&&("reading"===e?(l.state="awaitingMessage",l._messageIdSeq++,null===(t=l._await...<omitted>...)} could not be cloned.
    at http://localhost:3000/static/js/main.bd11f364.js:2:212380
    at new Promise (<anonymous>)
    at C (http://localhost:3000/static/js/main.bd11f364.js:2:212080)
    at Object.apply (http://localhost:3000/static/js/main.bd11f364.js:2:210833)
    at n.<anonymous> (http://localhost:3000/static/js/main.bd11f364.js:2:3973)
    at d (http://localhost:3000/static/js/main.bd11f364.js:2:196064)
    at Generator.<anonymous> (http://localhost:3000/static/js/main.bd11f364.js:2:197401)
    at Generator.next (http://localhost:3000/static/js/main.bd11f364.js:2:196427)
    at http://localhost:3000/static/js/main.bd11f364.js:2:2166
```

**Comment by batmilkyway** [comment]
I did try `no-fallback` but that didn't do anything unfortunately.

**Comment by batmilkyway** [comment]
Ok so after more digging I'm more convinced this is a babel thing and not a loader thing, so I will be closing this issue as it's not really related to anything to do with Papyros itself and mainly compatibility with the dependencies, like `pyodide-worker-runner`/`comsync`/`comlink`, with the create-react-app config.

I tried converting the application to use vitejs, but vite couldn't work with `pyodide-worker-runner` (vite supports either module or classic workers which means no mixing of `import` and `importScripts`). I have some more experiments I plan on running with other tools, like `swc` to see what could work.

The summary of the issue is that the code that is sent over to the python worker is being transpiled to a function in production, but something else in development. Functions can't be serialized via the structured cloning algorithm that is used (see https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm). _Specifically_ it seems to be [syncMessageCallback in comsync](https://github.com/alexmojaki/comsync/blob/2093797e370b97d1294641380141fdd98335e4fe/lib/index.ts#L65)

**Comment by winniederidder** [comment]
I believe @alexmojaki has already managed to get this kind of functionality to work in a React app, so maybe he can help with figuring out what the right configuration is for your needs.

**Comment by batmilkyway** [comment]
Yes, I created an issue in his `comsync` library, https://github.com/alexmojaki/comsync/issues/6. In the end, the actual issue was in `comlink`, but because it's been over a year since significant work on it I decided to fork it with a fix suggested in one of the issues, and then form `comsync` and `sync-message` to point to the forked `comlink`.

Quite hacky, but at least it works in a production build now https://glittering-narwhal-96bc3e.netlify.app/
