### ISSUE TITLE
Document CodeMirror features

### ISSUE THREAD

**Issue by winniederidder** [dodona-edu/papyros#46]
As mentioned by @bmesuere on #33 , the used features of CodeMirror should be documented.
I propose doing this by explicitly installing the items used in @codemirror/basicsetup and adding them as extensions. In this way, configuring them will be easier as well (as this is a part of e.g. #40 and #42)

**Comment by pdawyndt** [comment]
Could you also explicitly list features of CoderMirror that currently aren't supported by Papyros.
