### ISSUE TITLE
Update mouse pointer after code execution terminates

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/papyros#47]
After code execution terminates, the mouse pointer only changes to its default value after the mouse is moved away from the `Run` button. Would be better if the mouse pointer always changes, even if position of mouse remains above the `Run` button.

**Comment by winniederidder** [comment]
This seems to work fine for me on https://docs.dodona.be/papyros/.

**Comment by bmesuere** [comment]
I also cannot reproduce this on chrome on mac.

**Comment by winniederidder** [comment]
I will close this issue then until further notice.
