### ISSUE TITLE
First integration in Dodona

### ISSUE THREAD

**Issue by winniederidder** [dodona-edu/papyros#51]
This issue groups all issues that need to be tackled before being able to integrate Papyros into Dodona to perform a try-out. For this, the layout should be optimized so that everything is straightforward to use, as our target audience does not have experience with the complex interface of an IDE. We also want functionality that enhances the programming experience itself.

- [x] #2 
- [x] #43 
- [ ] #37 
- [x] #49 
- [ ] #50

Useful, but not strictly required:
- [ ] #1

**Comment by bmesuere** [comment]
I have created a 0.1 milestone, so this issue became redundant.
