### ISSUE TITLE
Switch languages without page reload

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/papyros#67]
Can we switch (natural) languages without reloading the page? With a page reload, the current state gets lost (code, input, output, ...).

**Comment by winniederidder** [comment]
Dodona itself also uses a page refresh to do this. Is there a use case for people programming first, then realizing the locale doesn't suit them to then change this locale?

**Comment by aroberge** [comment]
> Is there a use case for people programming first, then realizing the locale doesn't suit them to then change this locale?

There might be situations where poeple do not bother to change language before entering code and then get some feedback (for example, after a Python traceback) and realize that they would like to get feedback in a different language.
