### ISSUE TITLE
Toggle between batch and single-line input mode

### ISSUE THREAD

**Issue by winniederidder** [dodona-edu/papyros#68]
The current layout for handling input is a bit confusing. A toggle between batch mode (giving multiple inputs beforehand) and single-line (a single input area that is cleared upon pressing enter) would help making it clear when and where to enter data for the program.

**Comment by pdawyndt** [comment]
For what it's worth: CodeMirror has support to make ranges of text [styled, read-only, or atomic](https://codemirror.net/doc/manual.html#markText). May be useful to integrate input and output in the same field.
