### ISSUE TITLE
Provide file explorer

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/papyros#73]
Since WASI emulates a file system, Pyodide can read/write files. This already allows to produce and consume files from within Python code:

```python
message = 'And now for something completely different!'

with open('data.txt', 'w') as data:
    print(message, file=data)

with open('data.txt') as data:
    print(data.read(), end='')
```

Would also be nice if Papyros as an IDE gives userfriendly access to this file system (open existing files  as tabs, create new files/directories, ...).

**Comment by pdawyndt** [comment]
Currently, files are cleared between runs. Question is whether we want to retain them (maybe files from file explorer have to be injected in every runtime environment).

**Comment by winniederidder** [comment]
> Currently, files are cleared between runs. Question is whether we want to retain them (maybe files from file explorer have to be injected in every runtime environment).

Files no longer seem to be cleared between runs. Terminating the worker during an infinite loop causes the files to be lost. Best way to tackle this sounds like keeping track of files in a component on the main thread and capturing file events in the workers to also be sent to the main thread. Then files can be restored to the running backend after restarting. So this feature could turn out to be quite tricky.

**Comment by winniederidder** [comment]
Closing in favor of #182
