### ISSUE TITLE
Hide spinner when buttons are disabled

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/papyros#78]
When hovering over a disabled button, the mouse pointer shows a spinner. This even happens while the page is loading (run button disabled) or after the page has loaded (stop and enter buttons).

**Comment by winniederidder** [comment]
@pdawyndt The buttons show a blocking icon, or do you refer to this icon as a spinner? The style classes for these buttons have been updated recently, which should allow closing this issue.

**Comment by winniederidder** [comment]
@pdawyndt Does the thumbs-up reaction imply that this issue can be closed again?

**Comment by pdawyndt** [comment]
Yep.
