### ISSUE TITLE
Code completion annoyance

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/papyros#81]
If you manually enter `[]` you'll end up with `[]]`. Happens in Google Chrome on Windows 10. Does not happen on my iPad.

**Comment by winniederidder** [comment]
I do not seem to have this issue (also Chrome, Windows 10). Works for both instantly closing the brackets yourself, as well as filling in elements. Issue only happens when I add elements on separate lines. Does it occur for you even for empty lists?

**Comment by pdawyndt** [comment]
OK, it no longer seems to happen. Will close this issue for now (until I would see it happening again).
