### ISSUE TITLE
Support plotting in Safari

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/papyros#87]
Also give Safari users superpower to run code like this in Papyros:

![image](https://user-images.githubusercontent.com/5736113/146984502-4d2170c9-8f03-4aac-a6ec-fb9f1ae1aab5.png)

**Comment by pdawyndt** [comment]
Just looking for some nice plotting example:

![image](https://user-images.githubusercontent.com/5736113/147138484-02dd8265-c19b-493e-9692-398608f656c7.png)

```python
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx

plt.rcParams["font.size"] = 10
plt.figure()
plt.title('Random graph')

plt.tick_params(
    axis='both', left='off', top='off', right='off', 
    bottom='off', labelleft='off', labeltop='off', 
    labelright='off', labelbottom='off'
)
G = nx.random_geometric_graph(256, 0.125)
pos=nx.spring_layout(G)
nx.draw_networkx_edges(G, pos, alpha=0.2)
nx.draw_networkx_nodes(G, pos, node_color='r', node_size=12)

plt.show()
```

**Comment by pdawyndt** [comment]
Plotting now works on my iPad, but: network plot (above) always works, but matplotlib example only works on first execution.

**Comment by pdawyndt** [comment]
Matplotlib example of Network now works on all executions. However, it fails if 512 nodes are rendered instead of 256. Explicitly reporting solves the issue, but this should not be necessary. Seems like a shortcoming of dynamic loading of Python modules.

**Comment by winniederidder** [comment]
The dynamic loading of Python modules handles modules that you explicitly mention in your file. In this case, scipy seems to be a peer dependency that is only loaded in when the amount of data exceeds a certain threshold. In this case, we could wrap the execution with a try-except for ModuleNotFound-errors as such issues should not occurr.
