### ISSUE TITLE
Keep code after page reload

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/papyros#89]
Should avoid that (inexerienced or experienced whatsoever) programmers loose their code after a page reload.

**Comment by winniederidder** [comment]
This will only be available in the standalone-version, as it does not sound like expected behaviour in projects using Papyros (such as Dodona)

**Comment by winniederidder** [comment]
Yes, with likely a listener attached to the editor to update the value in localStorage every so often to not cost too much processing.
