### ISSUE TITLE
Check Loguru tracebacks 

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/papyros#90]
Loguru: https://github.com/Delgan/loguru

**Comment by winniederidder** [comment]
Is this specifically to evaluate how Logurue Exception tracebacks compare to those provided by FriendlyTraceback? They don't seem to add more information than we already have and integration would disrupt the python_runner workflow, so it doesn't appear worth it to investigate this library further.

**Comment by alexmojaki** [comment]
Loguru/better-exceptions basically just show variable values with nice 'arrows'. stack_data provides all the same information and more, and you can render it however you want in HTML.
